version: '3.8'

services:

  postgres_db:
    image: postgres:16.2
    environment:   # Set up postgres database name and password
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_board
      POSTGRES_USER: root
    ports:    # Set up ports exposed for other containers to connect to
      - 8432:5432
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d    

  task_board_api:
    build:
      context: "./Backend"
      dockerfile: "./Task Board API/Dockerfile"
    depends_on:
      - postgres_db
    command:
      tail -f /dev/null
    environment:   # Set up postgres database name and password
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_board
      POSTGRES_PORT: 5432
      POSTGRES_SERVER: postgres_db
    ports:    # Set up ports exposed for other containers to connect to
      - 7017:8080
      - 7018:8081
